name: chipmunk_flutter
description: chipmunk

# apk > flutter build apk —release --flavor dev -t lib/main/dev.dart
# 빌드 > flutter packages pub run build_runner build --delete-conflicting-outputs
# assets > fluttergen -c /Users/hyeokshin/StudioProjects/fortune-flutter/pubspec.yaml

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0-204.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.9.0
  firebase_remote_config: ^4.0.0
  firebase_analytics: ^10.2.0
  firebase_crashlytics: ^3.1.0
  app_settings: ^4.2.0

  # ui
  cupertino_icons: ^1.0.5
  flutter_svg: ^1.1.6
  expansion_widget: ^0.0.3
  lottie: ^2.3.2
  material_dialogs: ^1.1.4
  page_view_indicators: ^2.0.0
  location: ^4.4.0
  image_picker: ^0.8.7+1
  image_cropper: ^3.0.2
  flutter_animation_progress_bar: ^2.3.1
  flutter_keyboard_visibility: ^5.4.0
  item_selector: ^0.2.0
  scroll_to_index: ^3.0.1
  awesome_dialog: ^3.0.2
  alt_sms_autofill: ^1.0.0
  pin_code_fields: ^7.4.0
  double_back_to_close: ^2.0.0
  avatar_glow: ^2.0.2
  delayed_display: ^2.0.0
  flutter_svg_provider: ^1.0.3
  add_to_cart_animation: ^2.0.3
  image: ^4.0.15
  scrollable_list_tab_scroller: ^1.1.0

  # map
  flutter_map: ^3.1.0
  latlong2: ^0.8.1
  geolocator: ^9.0.2

  # state and dependency mgmt
  bloc_concurrency: ^0.2.1
  get_it: ^7.2.0
  flutter_bloc: ^8.1.2
  side_effect_bloc: ^1.0.0
  bloc_event_transformers: ^1.0.1
  bloc: ^8.1.1
  fluro: ^2.0.5

  # dart
  equatable: ^2.0.5
  dartz: ^0.10.1
  json_annotation: ^4.8.0
  synchronized: ^3.0.1
  logger: ^1.3.0
  easy_localization: ^3.0.1

  # network
  http: ^0.13.5
  chopper: ^6.1.1
  jwt_decoder: 2.0.1
  stomp_dart_client: ^0.4.4

  # data
  single_item_storage: ^1.0.5
  single_item_secure_storage: ^0.1.0
  single_item_shared_prefs: ^0.0.4
  shared_preferences: ^2.1.0
  flutter_screenutil: ^5.7.0
  freezed_annotation: ^2.2.0
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

  flutter_gen_runner:

  flutter_lints: ^2.0.1
  # 패키지명변경: flutter pub run change_app_package_name:main com.new.package.name
  change_app_package_name: ^1.1.0
  # For testing.
  mockito: ^5.3.2
  # Code generator
  build_runner: ^2.3.3
  # Code generator from models (to json and from json)
  json_serializable: ^6.6.1
  # Freezed
  freezed: ^2.3.2
  # API code generator
  chopper_generator: ^6.0.0

  test: any
  # navigation testing
  bloc_test: ^9.1.1

flutter_gen:
  output: lib/core/gen/
  lineLength: 80

  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

  colors:
    inputs:
      - assets/color/colors.xml

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/translations/
    - assets/images/
    - assets/icons/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Thin.ttf
          weight: 100
    - family: Pretendard-ExtraLight
      fonts:
        - asset: assets/fonts/Pretendard-ExtraLight.ttf
          weight: 200
    - family: Pretendard-Light
      fonts:
        - asset: assets/fonts/Pretendard-Light.ttf
          weight: 300
    - family: Pretendard-Regular
      fonts:
        - asset: assets/fonts/Pretendard-Regular.ttf
          weight: 400
    - family: Pretendard-Medium
      fonts:
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 500
    - family: Pretendard-SemiBold
      fonts:
        - asset: assets/fonts/Pretendard-SemiBold.ttf
          weight: 600
    - family: Pretendard-Bold
      fonts:
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700
    - family: Pretendard-ExtraBold
      fonts:
        - asset: assets/fonts/Pretendard-ExtraBold.ttf
          weight: 800
    - family: Pretendard-Black
      fonts:
        - asset: assets/fonts/Pretendard-Black.ttf
          weight: 900